name:                runnah
version:             0.1.0.0
github:              "krystalcode/hs-runnah"
license:             GPL-3.0-only
author:              "Dimitris Bozelos"
maintainer:          "Dimitris Bozelos <dbozelos@gmail.com>"
copyright:           "2024 Dimitris Bozelos"

# Extra files (if any) to be distributed with the source files of the
# package:
extra-source-files:
  - README.org
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A tool for running containers in development environments.
category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/krystalcode/hs-runnah>

# Dependencies applicable to all components:
dependencies:
  - base >= 4.7 && < 5
  - iris >= 0.1.0.0
  - mtl
  - optparse-applicative
  - text

# GHC options (if any) common to all components:
ghc-options:
  # These GHC flags affect which warnings GHC will emit:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wmissing-deriving-strategies
  # Makes build output nicer:
  - -fhide-source-paths

library:
  source-dirs: src

executables:
  runnah:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      # Link the program with the 'threaded' version of GHC's runtime system:
      - -threaded
      # Make all of GHC's runtime system (RTS) options available:
      - -rtsopts
      # Compile so as to use simultaneous threads when running the program,
      # based on how many processors are in the machine.
      - -with-rtsopts=-N
    dependencies:
      - runnah

tests:
  runnah-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - runnah

benchmarks:
  runnah-benchmark:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gauge
      - runnah
